---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: debian-7.8
  - name: debian-8.2

suites:
  - name: default
    run_list:
      - recipe[site-forumtypo3org::default]
    attributes:
      site-forumtypo3org:
        ssl_certificate: wildcard.vagrant
